server:
    port: 8080
spring:
    ai:
        dashscope:
            api-key: ${AI_DASHSCOPE_API_KEY}
            chat:
                options:
                    model: qwen-turbo
    application:
        name: ai-chat-ali

medical:
    cnn:
        url: http://localhost:5000/api/pneumonia/predict
        enabled: true
    vllm:
        url: http://localhost:8000/v1/chat/completions
        model: qwen3-0.6b
        enabled: true
