server:
  port: 8080
spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      milvus:
        client:
          host: 127.0.0.1
          port: 19530
        collection-name: rag_java_demo
        embedding-dimension: 1024
        metric-type: COSINE
        initialize-schema: true
    openai:
      api-key: EMPTY
      base-url: http://localhost:9901
      chat:
        options:
          model: qwen3-medical
          temperature: 0.3
        completions-path: /v1/chat/completions
  application:
    name: ai-chat-ali
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


app:
  upload:
    dir: uploads
  samples:
    dir: samples

medical:
  cnn:
    url: http://localhost:9801/api/pneumonia/predict
    enabled: true
  vllm:
    url: http://localhost:9901/v1/chat/completions
    model: qwen3-0.6b
    enabled: true

logging:
  level:
    root: INFO
    ff.pro: DEBUG
    org.springframework.ai: DEBUG